version: '3'

services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: servicio_producto
    volumes:
      - .:/servicio_producto
    ports:
      - "8000:8000"